#!/usr/bin/env php
<?php

use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

    // Get the current directory
//    $currentDirectory = __DIR__.'/vendor';
//
//    // Get the list of files and directories in the current directory
//    $contents = scandir($currentDirectory);
//
//    // Print the contents
//    foreach ($contents as $item) {
//        echo $item . PHP_EOL;
//    }

    echo(__DIR__);

//    dd('dd');

// Register the Composer autoloader...
require __DIR__.'/vendor/autoload.php';

// Bootstrap Laravel and handle the command...
$status = (require_once __DIR__.'/bootstrap/app.php')
    ->handleCommand(new ArgvInput);

exit($status);
